import { Question } from '../types';

export const ALL_QUESTIONS: Question[] = [
  // --- Requisitos Gerais ---
  {
    id: 'RG1.1',
    topic: 'Requisitos Gerais',
    subtopic: 'Divulgação Integrada',
    text: 'O relatório IFRS S1 está em conformidade com as Demonstrações Financeiras (DFs), sendo ambos referentes à mesma entidade reportadora e às mesmas organizações subsidiárias?',
    type: 'boolean',
    evidence_prompt: 'Confirme o nome da entidade reportadora e as DFs relacionadas. Forneça evidências (ex: trecho do relatório) que comprovem a consistência.',
    reference: 'IFRS S1, §20',
    priority: 'imperative',
    reference_text: "An entity's sustainability-related financial disclosures shall be for the same reporting entity as the related financial statements."
  },
  {
    id: 'RG1.2',
    topic: 'Requisitos Gerais',
    subtopic: 'Divulgação Integrada',
    text: 'O relatório descreve a entidade reportadora, informando sobre as atividades realizadas e empresas subsidiárias contempladas?',
    type: 'boolean',
    evidence_prompt: 'Indique onde esta descrição pode ser encontrada e anexe trechos relevantes que demonstrem a abrangência da descrição.',
    reference: 'IFRS S1, §13',
    priority: 'imperative',
  },
  {
    id: 'RG2.1',
    topic: 'Requisitos Gerais',
    subtopic: 'Divulgação Integrada',
    text: 'A entidade fornece informações de forma a permitir que os usuários compreendam as conexões entre os vários riscos e oportunidades, e entre as divulgações de sustentabilidade e os outros relatórios financeiros?',
    type: 'boolean',
    evidence_prompt: 'Descreva como a entidade garante a conectividade das informações (ex: referências cruzadas, narrativa integrada) e anexe exemplos do relatório.',
    reference: 'IFRS S1, §21',
    priority: 'moderate'
  },
  {
    id: 'RG3.1',
    topic: 'Requisitos Gerais',
    subtopic: 'Divulgação Integrada',
    text: 'A entidade identifica as demonstrações financeiras a que as divulgações de sustentabilidade se referem?',
    type: 'boolean',
    evidence_prompt: 'Forneça a identificação exata das demonstrações financeiras referenciadas, conforme divulgado no relatório.',
    reference: 'IFRS S1, §22',
    priority: 'imperative'
  },
  {
    id: 'RG4.1',
    topic: 'Requisitos Gerais',
    subtopic: 'Divulgação Integrada',
    text: 'Os dados e premissas utilizados nas divulgações de sustentabilidade são consistentes com os utilizados nas demonstrações financeiras, na medida do possível?',
    type: 'boolean',
    evidence_prompt: 'Descreva como a consistência é mantida ou explique e anexe evidências de quaisquer inconsistências relevantes.',
    reference: 'IFRS S1, §23',
    priority: 'moderate'
  },
  {
    id: 'RG5.1',
    topic: 'Requisitos Gerais',
    subtopic: 'Divulgação Integrada',
    text: 'A unidade monetária utilizada no reporte de Sustentabilidade é a mesma do reporte financeiro?',
    type: 'boolean',
    evidence_prompt: 'Confirme a moeda de apresentação utilizada e indique a página do relatório onde essa informação pode ser encontrada.',
    reference: 'IFRS S1, §24',
    priority: 'non-priority'
  },

  // --- Governança ---
  {
    id: 'GV1.1',
    topic: 'Governança',
    subtopic: 'Supervisão do Órgão de Governança',
    text: 'A entidade divulga informações sobre os processos de governança, controles e procedimentos que utiliza para monitorar e gerir riscos e oportunidades relacionados à sustentabilidade (SRROs)?',
    type: 'boolean',
    evidence_prompt: 'Anexe a política de governança ou o trecho do relatório que descreve os processos, controles e procedimentos para SRROs.',
    reference: 'IFRS S1, §26',
    priority: 'imperative'
  },
  {
    id: 'GV2.1',
    topic: 'Governança',
    subtopic: 'Supervisão do Órgão de Governança',
    text: 'Qual órgão de governança ou indivíduo é responsável pela supervisão dos SRROs?',
    type: 'single_choice',
    options: ['Conselho de Administração', 'Comitê de Sustentabilidade', 'Comitê de Auditoria', 'Outro'],
    evidence_prompt: 'Forneça o trecho do estatuto, regimento interno ou ata de reunião que designa esta responsabilidade.',
    reference: 'IFRS S1, §27(a)',
    priority: 'imperative',
  },
  {
    id: 'GV2.2',
    topic: 'Governança',
    subtopic: 'Supervisão do Órgão de Governança',
    text: 'A instituição informa como as habilidades e competências em relação aos SRROs são avaliadas ou desenvolvidas no corpo de governança?',
    type: 'boolean',
    evidence_prompt: 'Descreva o processo de avaliação de competências e/ou o plano de desenvolvimento. Anexe atas ou relatórios relevantes.',
    reference: 'IFRS S1, §27(a)(ii)',
    priority: 'moderate',
  },
  {
    id: 'GV2.3',
    topic: 'Governança',
    subtopic: 'Supervisão do Órgão de Governança',
    text: 'A instituição divulga quando e com qual frequência os membros do corpo de governança são informados sobre os SRROs?',
    type: 'boolean',
    evidence_prompt: 'Especifique a frequência e os momentos (ex: reuniões trimestrais do conselho) e anexe o calendário de reuniões ou trecho da ata.',
    reference: 'IFRS S1, §27(a)(iii)',
    priority: 'moderate',
  },
  {
    id: 'GV2.4',
    topic: 'Governança',
    subtopic: 'Supervisão do Órgão de Governança',
    text: 'É divulgado como o corpo de governança avalia a definição de metas relacionadas aos SRROs e monitora seu progresso?',
    type: 'boolean',
    evidence_prompt: 'Descreva o processo de avaliação e monitoramento de metas pela governança e anexe evidências (ex: painéis de controle, atas).',
    reference: 'IFRS S1, §27(a)(v)',
    priority: 'moderate',
  },
  {
    id: 'GV3.1',
    topic: 'Governança',
    subtopic: 'Papel da Gestão',
    text: 'A entidade divulga o papel da gestão nos processos de governança, incluindo qualquer delegação de responsabilidades?',
    type: 'boolean',
    evidence_prompt: 'Descreva o papel da gestão e, se aplicável, o cargo ou comitê ao qual as responsabilidades foram delegadas. Anexe a matriz de responsabilidades.',
    reference: 'IFRS S1, §27(b)',
    priority: 'moderate',
  },
  {
    id: 'GV3.2',
    topic: 'Governança',
    subtopic: 'Papel da Gestão',
    text: 'É divulgado se a gestão utiliza controles e procedimentos para auxiliar no acompanhamento dos SRROs?',
    type: 'boolean',
    evidence_prompt: 'Descreva os controles e procedimentos de gestão, e como estão integrados a outras funções internas. Anexe fluxogramas ou manuais de procedimento.',
    reference: 'IFRS S1, §27(b)(ii)',
    priority: 'non-priority',
  },

  // --- Estratégia ---
  {
    id: 'ES1.1',
    topic: 'Estratégia',
    subtopic: 'Identificação de Riscos e Oportunidades',
    text: 'A entidade divulga sua abordagem estratégica para gerir SRROs?',
    type: 'boolean',
    evidence_prompt: 'Anexe o capítulo de estratégia do relatório de sustentabilidade ou a política de gestão de SRROs.',
    reference: 'IFRS S1, §28',
    priority: 'imperative'
  },
  {
    id: 'ES2.1',
    topic: 'Estratégia',
    subtopic: 'Identificação de Riscos e Oportunidades',
    text: 'A entidade descreve os SRROs que podem afetar suas perspectivas, especificando os horizontes temporais (curto, médio, longo prazo)?',
    type: 'text_block',
    evidence_prompt: 'Liste os principais SRROs e os horizontes de tempo associados. Explique como a entidade define cada horizonte temporal.',
    reference: 'IFRS S1, §30-31',
    priority: 'imperative',
  },
  {
    id: 'ES3.1',
    topic: 'Estratégia',
    subtopic: 'Impacto no Modelo de Negócios',
    text: 'A entidade descreve os efeitos atuais e previstos dos SRROs em seu modelo de negócios e cadeia de valor?',
    type: 'text_block',
    evidence_prompt: 'Forneça a descrição dos efeitos atuais e previstos e indique onde, na cadeia de valor, esses SRROs estão concentrados (anexe mapa da cadeia de valor, se houver).',
    reference: 'IFRS S1, §32',
    priority: 'moderate',
  },
  {
    id: 'ES4.1',
    topic: 'Estratégia',
    subtopic: 'Planejamento e Resposta Estratégica',
    text: 'Apresenta como a entidade respondeu e planeja responder aos SRROs na sua estratégia e tomada de decisão, incluindo o progresso sobre planos de períodos anteriores?',
    type: 'text_block',
    evidence_prompt: 'Descreva a resposta estratégica, os planos, os trade-offs considerados e o progresso (qualitativo e quantitativo) em relação a planos passados.',
    reference: 'IFRS S1, §33',
    priority: 'moderate',
  },
  {
    id: 'ES5.1',
    topic: 'Estratégia',
    subtopic: 'Planejamento e Resposta Estratégica',
    text: 'A entidade divulga os efeitos atuais e antecipados dos SRROs em sua posição financeira, desempenho e fluxos de caixa?',
    type: 'boolean',
    evidence_prompt: 'Descreva os efeitos financeiros atuais e previstos, fornecendo informações quantitativas e qualitativas. Anexe os trechos relevantes das demonstrações financeiras e do relatório.',
    reference: 'IFRS S1, §34',
    priority: 'imperative',
  },
  {
    id: 'ES5.2',
    topic: 'Estratégia',
    subtopic: 'Planejamento e Resposta Estratégica',
    text: 'Apresenta como esses SRROs e as estratégias para gerenciá-los são levados em consideração no planejamento financeiro da empresa?',
    type: 'boolean',
    evidence_prompt: 'Descreva como os SRROs são integrados no planejamento financeiro. Anexe o plano de investimentos e alocação de capital relacionado.',
    reference: 'IFRS S1, §35',
    priority: 'moderate',
  },
  {
    id: 'ES5.3',
    topic: 'Estratégia',
    subtopic: 'Planejamento e Resposta Estratégica',
    text: 'A entidade conseguiu mensurar os efeitos financeiros antecipados dos SRROs?',
    type: 'boolean',
    evidence_prompt: 'Anexe a seção do relatório que contém os dados quantitativos sobre os efeitos financeiros antecipados.',
    reference: 'IFRS S1, §38',
    priority: 'non-priority',
  },
  {
    id: 'ES5.4',
    topic: 'Estratégia',
    subtopic: 'Planejamento e Resposta Estratégica',
    text: 'Em caso de não mensuração, a entidade explica o porquê da ausência da informação quantitativa?',
    type: 'boolean',
    evidence_prompt: 'Anexe a justificativa para a não divulgação (ex: impossível identificar separadamente, incerteza elevada, falta de recursos).',
    reference: 'IFRS S1, §40(a)',
    priority: 'non-priority',
  },
  {
    id: 'ES5.5',
    topic: 'Estratégia',
    subtopic: 'Planejamento e Resposta Estratégica',
    text: 'Mesmo não divulgando dados quantitativos, a entidade informa sobre os dados qualitativos dos efeitos antecipados?',
    type: 'boolean',
    evidence_prompt: 'Indique onde as informações qualitativas sobre os efeitos antecipados são divulgadas e anexe o trecho correspondente.',
    reference: 'IFRS S1, §40(b)',
    priority: 'non-priority',
  },
  {
    id: 'ES6.1',
    topic: 'Estratégia',
    subtopic: 'Análise de Resiliência',
    text: 'A empresa divulga informações qualitativas e quantitativas sobre a resiliência de sua estratégia e modelo de negócios frente aos riscos de sustentabilidade?',
    type: 'text_block',
    evidence_prompt: 'Forneça a avaliação (qualitativa e/ou quantitativa) da resiliência da estratégia, incluindo a capacidade de se ajustar a incertezas. Anexe o estudo de resiliência.',
    reference: 'IFRS S1, §41',
    priority: 'moderate',
  },
  {
    id: 'ES6.2',
    topic: 'Estratégia',
    subtopic: 'Análise de Resiliência',
    text: 'A entidade utiliza análise de cenários climáticos para avaliar sua resiliência climática?',
    type: 'boolean',
    evidence_prompt: 'Descreva a avaliação de resiliência climática, incluindo informações sobre os cenários utilizados, premissas e como a análise foi realizada. Anexe o relatório de análise de cenários.',
    reference: 'IFRS S2, §22',
    priority: 'imperative',
  },
  {
    id: 'ES7.1',
    topic: 'Estratégia',
    subtopic: 'Gestão de Riscos Climáticos',
    text: 'Tópico(s) coberto(s) pela divulgação sobre o gerenciamento integrado de riscos (ou seja, quando fala da gestão de riscos climáticos, quais temas estão cobertos).',
    type: 'text_block',
    evidence_prompt: 'Liste os temas climáticos cobertos e anexe a seção do relatório que descreve a gestão integrada de riscos.',
    reference: 'IFRS S2.26',
    priority: 'moderate',
  },

  // --- Gestão de Riscos ---
  {
    id: 'GR1.1',
    topic: 'Gestão de Riscos',
    subtopic: 'Processos de Gestão de Risco',
    text: 'A entidade divulga as políticas e os processos que utiliza para identificar, avaliar, priorizar e monitorar SRROs?',
    type: 'boolean',
    evidence_prompt: 'Anexe a política de gestão de riscos e oportunidades de sustentabilidade ou o manual de procedimentos.',
    reference: 'IFRS S1, §43-44',
    priority: 'imperative'
  },
  {
    id: 'GR1.2',
    topic: 'Gestão de Riscos',
    subtopic: 'Integração e Análise',
    text: 'Os processos de gestão de SRROs estão integrados ao processo geral de gestão de riscos da entidade?',
    type: 'boolean',
    evidence_prompt: 'Descreva como os processos estão integrados e como eles informam a gestão de risco geral. Anexe o fluxograma do processo integrado.',
    reference: 'IFRS S1, §44(c)',
    priority: 'moderate',
  },
  {
    id: 'GR1.3',
    topic: 'Gestão de Riscos',
    subtopic: 'Integração e Análise',
    text: 'A entidade utiliza análise de cenários climáticos para informar a identificação de riscos relacionados ao clima?',
    type: 'boolean',
    evidence_prompt: 'Descreva como a análise de cenários é usada para identificar riscos climáticos e anexe a seção relevante do estudo.',
    reference: 'IFRS S2, §25(a)(ii)',
    priority: 'moderate',
  },
    
  // --- Métricas e Metas ---
  {
    id: 'MM1.1',
    topic: 'Métricas e Metas',
    subtopic: 'Métricas de Desempenho',
    text: 'É divulgada a performance da entidade em relação aos SRROs, incluindo o progresso acerca dos alvos que a organização estipulou ou é requerida por lei?',
    type: 'boolean',
    evidence_prompt: 'Anexe o capítulo de "Métricas e Metas" ou "Desempenho de Sustentabilidade" do relatório.',
    reference: 'IFRS S1, §45',
    priority: 'imperative'
  },
  {
    id: 'MM2.1',
    topic: 'Métricas e Metas',
    subtopic: 'Métricas de Desempenho',
    text: 'Para cada SRRO material, a entidade divulga as métricas que utiliza para medir e monitorar seu desempenho?',
    type: 'boolean',
    evidence_prompt: 'Anexe a tabela ou lista de métricas por SRRO material.',
    reference: 'IFRS S1, §46',
    priority: 'imperative',
  },
  {
    id: 'MM2.2',
    topic: 'Métricas e Metas',
    subtopic: 'Métricas de Desempenho',
    text: 'A entidade divulga as premissas e os processos utilizados para definir as métricas?',
    type: 'boolean',
    evidence_prompt: 'Para cada métrica, anexe a metodologia, as premissas e os processos de cálculo ou definição.',
    reference: 'IFRS S1, §50',
    priority: 'moderate',
  },
  {
    id: 'MM2.3',
    topic: 'Métricas e Metas',
    subtopic: 'Métricas de Desempenho',
    text: 'Lista de métricas relacionadas a riscos e oportunidades climáticos.',
    type: 'text_block',
    evidence_prompt: 'Forneça a lista de métricas utilizadas para riscos e oportunidades relacionados ao clima, conforme divulgado.',
    reference: 'IFRS S1.46, IFRS S2.27',
    priority: 'imperative',
  },
  {
    id: 'MM3.1',
    topic: 'Métricas e Metas',
    subtopic: 'Definição de Metas',
    text: 'A entidade divulga detalhes sobre as metas de sustentabilidade que estabeleceu?',
    type: 'text_block',
    evidence_prompt: 'Para cada meta, descreva a métrica utilizada, o período, o desempenho em relação à meta, e quaisquer marcos intermediários. Anexe a tabela de metas do relatório.',
    reference: 'IFRS S1, §51',
    priority: 'imperative',
  },
  {
    id: 'MM3.2',
    topic: 'Métricas e Metas',
    subtopic: 'Definição de Metas',
    text: 'Métricas utilizadas para definir objetivos e monitorar progresso em relação aos riscos e oportunidades climáticos.',
    type: 'text_block',
    evidence_prompt: 'Descreva as métricas usadas para definir e acompanhar os objetivos climáticos. Anexe a tabela de desempenho ou a seção relevante do relatório.',
    reference: 'IFRS S1.51(a), IFRS S2.33(a)',
    priority: 'moderate',
  },
  {
    id: 'MM4.1',
    topic: 'Métricas e Metas',
    subtopic: 'Emissões de GEE',
    text: 'A entidade divulga suas emissões de GEE brutas absolutas para Escopo 1, 2 e 3?',
    type: 'boolean',
    evidence_prompt: 'Anexe o inventário de emissões de GEE ou a tabela correspondente do relatório.',
    reference: 'IFRS S2, §29(a)(i)',
    priority: 'imperative'
  },
  {
    id: 'MM4.2',
    topic: 'Métricas e Metas',
    subtopic: 'Emissões de GEE',
    text: 'A entidade divulga a abordagem utilizada para medir suas emissões de GEE?',
    type: 'text',
    evidence_prompt: 'Descreva a abordagem de medição (ex: GHG Protocol), os inputs e as premissas utilizadas. Anexe a nota metodológica do inventário.',
    reference: 'IFRS S2, §29(a)(iii)',
    priority: 'moderate',
  },
  {
    id: 'MM4.3',
    topic: 'Métricas e Metas',
    subtopic: 'Emissões de GEE',
    text: 'Detalhes do que está incluso nas Emissões GHG de Escopo 3.',
    type: 'text_block',
    evidence_prompt: 'Descreva em detalhes o que compõe as emissões de Escopo 3 reportadas. Anexe a memória de cálculo ou nota metodológica.',
    reference: 'IFRS S2.29(a)(vi)(1)',
    priority: 'moderate',
  },
  {
    id: 'MM4.4',
    topic: 'Métricas e Metas',
    subtopic: 'Emissões de GEE',
    text: 'Quais categorias estão inclusas na mensuração de Emissões GHG de Escopo 3?',
    type: 'multiple_choice',
    options: [
        'Categoria 1 - Bens e serviços adquiridos',
        'Categoria 2 - Bens de capital',
        'Categoria 3 - Atividades relacionadas a combustível e energia (não incluídas no Escopo 1 ou 2)',
        'Categoria 4 - Transporte e distribuição a montante',
        'Categoria 5 - Resíduos gerados nas operações',
        'Categoria 6 - Viagens de negócios',
        'Categoria 7 - Deslocamento de funcionários',
        'Categoria 8 - Ativos arrendados a montante',
        'Categoria 9 - Transporte e distribuição a jusante',
        'Categoria 10 - Processamento de produtos vendidos',
        'Categoria 11 - Uso de produtos vendidos',
        'Categoria 12 - Tratamento de fim de vida de produtos vendidos',
        'Categoria 13 - Ativos arrendados a jusante',
        'Categoria 14 - Franquias',
        'Categoria 15 - Investimentos',
    ],
    evidence_prompt: 'Selecione todas as categorias de Escopo 3 que são mensuradas e reportadas pela entidade. Anexe o inventário de GEE.',
    reference: 'IFRS S2.29(a)(vi)(1)',
    priority: 'moderate',
  },
  {
    id: 'MM5.1',
    topic: 'Métricas e Metas',
    subtopic: 'Exposição a Riscos Climáticos',
    text: 'A entidade divulga a exposição de seus ativos e atividades a riscos de transição climática?',
    type: 'text',
    evidence_prompt: 'Forneça o valor e a porcentagem de ativos ou atividades de negócio vulneráveis a riscos de transição. Anexe a análise de risco de transição.',
    reference: 'IFRS S2, §29(b)',
    priority: 'moderate'
  },
  {
    id: 'MM5.2',
    topic: 'Métricas e Metas',
    subtopic: 'Exposição a Riscos Climáticos',
    text: 'A entidade divulga a exposição de seus ativos e atividades a riscos físicos climáticos?',
    type: 'text',
    evidence_prompt: 'Forneça o valor e a porcentagem de ativos ou atividades de negócio vulneráveis a riscos físicos. Anexe a análise de risco físico.',
    reference: 'IFRS S2, §29(c)',
    priority: 'moderate'
  },
  {
    id: 'MM6.1',
    topic: 'Métricas e Metas',
    subtopic: 'Oportunidades e Investimento',
    text: 'A entidade divulga o alinhamento de seus ativos e atividades com oportunidades climáticas?',
    type: 'text',
    evidence_prompt: 'Forneça o valor e a porcentagem de ativos ou atividades de negócio alinhados com oportunidades relacionadas ao clima. Anexe o estudo de oportunidades.',
    reference: 'IFRS S2, §29(d)',
    priority: 'moderate'
  },
  {
    id: 'MM6.2',
    topic: 'Métricas e Metas',
    subtopic: 'Oportunidades e Investimento',
    text: 'A entidade divulga o capital direcionado para riscos e oportunidades climáticas?',
    type: 'text',
    evidence_prompt: 'Forneça o montante de CAPEX, financiamento ou investimento direcionado para riscos e oportunidades climáticas. Anexe o plano de investimentos.',
    reference: 'IFRS S2, §29(e)',
    priority: 'moderate'
  },
  {
    id: 'MM7.1',
    topic: 'Métricas e Metas',
    subtopic: 'Precificação de Carbono e Remuneração',
    text: 'A entidade utiliza preços internos de carbono em suas decisões?',
    type: 'boolean',
    evidence_prompt: 'Se sim, explique como a precificação interna de carbono é usada e quais são os preços por tonelada de emissão de GEE. Anexe a política de precificação de carbono.',
    reference: 'IFRS S2, §29(f)',
    priority: 'non-priority'
  },
  {
    id: 'MM7.2',
    topic: 'Métricas e Metas',
    subtopic: 'Precificação de Carbono e Remuneração',
    text: 'A entidade divulga como considerações climáticas são fatoradas na remuneração executiva?',
    type: 'boolean',
    evidence_prompt: 'Descreva como as considerações climáticas são incorporadas na remuneração e anexe a política de remuneração ou o trecho do relatório.',
    reference: 'IFRS S2, §29(g)',
    priority: 'moderate'
  },
  {
    id: 'MM8.1',
    topic: 'Métricas e Metas',
    subtopic: 'Metas Climáticas',
    text: 'Detalhes das metas de emissões GHG.',
    type: 'text_block',
    evidence_prompt: 'Forneça detalhes sobre as metas de GEE, incluindo o ano base, o ano alvo, o percentual de redução e se é uma meta absoluta ou de intensidade.',
    reference: 'IFRS S2.36(d)',
    priority: 'imperative',
  },
  {
    id: 'MM8.2',
    topic: 'Métricas e Metas',
    subtopic: 'Metas Climáticas',
    text: 'Gases de efeito estufa cobertos pela meta.',
    type: 'multiple_choice',
    options: [
      'Dióxido de carbono (CO2)',
      'Metano (CH4)',
      'Óxido nitroso (N2O)',
      'Hidrofluorcarbonetos (HFCs)',
      'Perfluorcarbonetos (PFCs)',
      'Hexafluoreto de enxofre (SF6)',
      'Trifluoreto de nitrogênio (NF3)',
    ],
    evidence_prompt: 'Selecione todos os gases cobertos pelas metas de GEE. Anexe a documentação da meta.',
    reference: 'IFRS S2.36(a)',
    priority: 'moderate',
  },
  {
    id: 'MM8.3',
    topic: 'Métricas e Metas',
    subtopic: 'Metas Climáticas',
    text: 'Quais escopos de emissões estão cobertos pelas metas?',
    type: 'multiple_choice',
    options: [
      'Escopo 1 (Emissões GHG)',
      'Escopo 2 (Emissões GHG)',
      'Escopo 3 (Emissões GHG)',
    ],
    evidence_prompt: 'Selecione todos os escopos de emissão cobertos pelas metas. Anexe a documentação da meta.',
    reference: 'IFRS S2.36(b)',
    priority: 'moderate',
  },
  
  // --- Fontes de Orientação e Conformidade ---
  {
    id: 'FC1.1',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Processo de Materialidade',
    text: 'A organização divulga os temas materiais relacionados à sustentabilidade que possam impactar nos ativos da companhia?',
    type: 'boolean',
    evidence_prompt: 'Anexe a matriz de materialidade ou a seção do relatório que descreve os temas materiais identificados.',
    reference: 'IFRS S1, §17',
    priority: 'imperative'
  },
  {
    id: 'FC1.2',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Processo de Materialidade',
    text: 'Ao avaliar a materialidade, a entidade considera fatores quantitativos e qualitativos, bem como o impacto potencial de eventos futuros incertos sobre os fluxos de caixa?',
    type: 'boolean',
    evidence_prompt: 'Descreva como a entidade aplica fatores quantitativos e qualitativos na sua avaliação de materialidade e anexe a metodologia de materialidade.',
    reference: 'IFRS S1, Appendix B',
    priority: 'moderate',
  },
  {
    id: 'FC2.1',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Fontes de Orientação',
    text: 'Na ausência de normas IFRS que se apliquem a um SRRO, a entidade utiliza seu julgamento para identificar informações relevantes?',
    type: 'boolean',
    evidence_prompt: 'Descreva o processo de julgamento para identificar divulgações relevantes para SRROs não cobertos por normas específicas.',
    reference: 'IFRS S1, §57',
    priority: 'non-priority',
  },
  {
    id: 'FC2.2',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Fontes de Orientação',
    text: 'Nesse julgamento, a entidade considera a aplicabilidade das métricas associadas aos tópicos inclusos no SASB Standards?',
    type: 'boolean',
    evidence_prompt: 'Especifique se e como as normas SASB foram consideradas e anexe a análise de aderência ao SASB.',
    reference: 'IFRS S1, §58(a)',
    priority: 'moderate',
  },
  {
    id: 'FC2.3',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Fontes de Orientação',
    text: 'Nesse julgamento, a entidade considera a aplicabilidade do CDSB Framework Application Guidance?',
    type: 'boolean',
    evidence_prompt: 'Especifique se e como o CDSB Framework foi considerado.',
    reference: 'IFRS S1, §58(b)(i)',
    priority: 'non-priority',
  },
  {
    id: 'FC2.4',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Fontes de Orientação',
    text: 'Nesse julgamento, a entidade referencia e considera a aplicabilidade de outros órgãos padronizadores e informações de empresas do mesmo setor/região?',
    type: 'boolean',
    evidence_prompt: 'Especifique quais outras fontes foram consideradas (outros órgãos, relatórios de pares) e anexe o benchmark.',
    reference: 'IFRS S1, §58(b)(ii-iii)',
    priority: 'non-priority',
  },
  {
    id: 'FC3.1',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Fontes de Orientação',
    text: 'Os standards específicos, pronunciamentos, práticas e outras fontes de embasamento que a entidade utilizou são identificáveis?',
    type: 'text',
    evidence_prompt: 'Liste as normas, pronunciamentos (incluindo guias de indústria) e outras fontes de orientação que a entidade aplicou.',
    reference: 'IFRS S1, §59',
    priority: 'moderate'
  },
  {
    id: 'FC4.1',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Estrutura do Relatório',
    text: 'O período relatado no IFRS Sustainability Disclosure é o mesmo do Financial Disclosure?',
    type: 'boolean',
    evidence_prompt: 'Confirme as datas e os períodos de reporte para ambos os relatórios, indicando a página onde a informação se encontra.',
    reference: 'IFRS S1, §64',
    priority: 'imperative'
  },
  {
    id: 'FC4.2',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Estrutura do Relatório',
    text: 'Em caso de mudança no período de reporte, a entidade divulga o período compreendido e a motivação?',
    type: 'boolean',
    evidence_prompt: 'Anexe a justificativa da mudança do período de reporte.',
    reference: 'IFRS S1, §66',
    priority: 'non-priority',
  },
  {
    id: 'FC5.1',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Estrutura do Relatório',
    text: 'A entidade divulga as informações de sustentabilidade como parte de seus relatórios financeiros de propósito geral?',
    type: 'single_choice',
    options: ['Relatório de Gestão', 'Relatório Anual Integrado', 'Outro Documento'],
    evidence_prompt: 'Especifique onde as divulgações de sustentabilidade podem ser encontradas e anexe o sumário do documento.',
    reference: 'IFRS S1, §60',
    priority: 'imperative'
  },
  {
    id: 'FC5.2',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Estrutura do Relatório',
    text: 'Caso as informações sejam incluídas por referência cruzada a outros relatórios, essa referência torna a informação claramente identificável e acessível nas mesmas condições?',
    type: 'boolean',
    evidence_prompt: 'Anexe um exemplo de referência cruzada do relatório e descreva como a entidade garante clareza e acessibilidade.',
    reference: 'IFRS S1, §63',
    priority: 'non-priority',
  },
  {
    id: 'FC6.1',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Declaração de Conformidade',
    text: 'A entidade faz uma declaração explícita e sem reservas de conformidade com os IFRS Sustainability Disclosure Standards?',
    type: 'boolean',
    evidence_prompt: 'Anexe a declaração de conformidade exata, conforme publicada no relatório.',
    reference: 'IFRS S1, §72',
    priority: 'imperative'
  }
];